name: minibuild
description: A simple in-memory incremental build graph thing.
environment:
  sdk: '^3.0.0'
dependencies:
  mime_type: ^1.0.0
  path: ^1.8.0
  shelf: ^1.1.4
  watcher: ^1.0.0
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.8
