name: betwixt
description: A template language.
environment:
  sdk: '^3.0.0'
dependencies:
  charcode: ^1.2.0
  intl: ^0.17.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0
dev_dependencies:
  coverage: ^1.0.3
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.17.9