name: journal
description: The static site generator for journal.stuffwithstuff.com.
environment:
  sdk: '^3.0.0'
dependencies:
  betwixt:
    path: ../betwixt # TODO: Make normal dependency.
  charcode: ^1.2.0
  chromatophore:
    path: ../chromatophore # TODO: Make normal dependency.
  collection: ^1.15.0
  markdown: ^4.0.0
  minibuild:
    path: ../minibuild # TODO: Make normal dependency.
  sass: ^1.37.5
  typographic_markdown:
    path: ../typographic_markdown # TODO: Make normal dependency.
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.8
