name: chromatophore
description: A customizable syntax highlighter.
environment:
  sdk: '^3.0.0'
dependencies:
  charcode: ^1.1.3
  markdown: ^4.0.0
  string_scanner: ^1.0.5
dev_dependencies:
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.16.3
