name: typographic_markdown
description: >
  A set of inline syntax extensions to the markdown package for writing
  non-ASCII typographic content using ASCII.
environment:
  sdk: '^3.0.0'
dependencies:
  charcode: ^1.2.0
  markdown: ^4.0.0
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.8
